language: python
python:
- '2.7'
install:
- ./test/install.sh
script: 
- source ~/.profile
- export MOMOPATH=.
- nosetests -w test
- momo help
- momo-mod help
- momo-mib help
- momo-hex help
- momo-gsm help
#- momo-pcb help #(help currently not supported)
- momo-reportinator help
- momo-sensor help
- momo-multisensor help
#- momo-picunit help #(help currently not supported)
deploy:
  provider: pypi
  user: welldone
  password:
    secure: R+2My9xlrw2RSzIe9bCCdecsfCnebp0ahMFpQHxKkadPCLTm8441PubrMUeTOqFrlO/uoZidl7uC9WWG3aen8ivortmNSE3yPMo4hP5r6kdQwffAQvqrZERrroOvl/q2edSxokmfxXxkdwqknyvvR49a9Q00c99waQhSHQwhlQs=
  on:
    repo: WellDone/pymomo
    tags: true
    all_branches: true
