language: python
env:
  global:
  - secure: V1T464SuuGIyyFzzWd6Wh8ekaHv5S0BIeJL+WFkZAuL3RHJ3ZsP12uHtdWbVusQqq0+dGI3+Q+L2EBspUcYkrtSTeu9Y3031yCAHTjQuP2wF/oQ979JyUF9WuNUR+Dw54WR1vkBwIMcFSF3UsElE+ByBX1nX12g/PX/sOAC2lah0r3jX6SFRpB+AV1SUne7VmwxAvP56XmCSoieO3se7NcExtBQzLJpkO+7kkZDenvn4J3aK1/SkziSIJmJddHgVif+yXioQCAncVFJNPVYrhx8Xv3r7EenYPjUG/fgRXBOcc/YkC1xq5JNLgQ7pQovi9zGMhNo2sNNi/tgpwbCK55gr5qJzbzsZYSl1aCLlD3/nAncWepxG20Ue68GOxzkxuSeNfNmGfqeNFUEoI6mRrmlJH9ebMxm0JyLPUav7pPXqxnqRrYZrRBqvu8u2Tw9dUGLVYSVv194vxWaCQMSmFJZdkoMujm2z8uBvgeIdwFim/TBgpVbT8V/9MUPvPmaawTcLlDEGUDHc4lzWhydqKu9nQCODs+T/jLHr9TE0KvwrLeM7bAySDVPXQl1+ORHDJJkt+kBwYbjNjjpkMD8RGhmlvd1V4ASnG9T6vvwEZYmFDQo9PDHrqNdEXpGwU0ypPnsBS3biDvejK3v/YfVwe1SFqle1uNIvhJYc58eQCF4=
  - secure: YxFDQfBFPPsoKK9hMmn5pjSpR4qKRbeRai/xmtWLvYZPeqWhOZfCc9VKt3cjMRnaP4nXTp2muzK4slkMfQHJVkqLaHy51mxzQ1arbH/jMctwB1i6ty0fFh2jyX4g6Iiz0vPhE8JKofgd/hQi4X97l3BoAzNlMSPWTfb+DyOAtTYugDUwgqYfDhgfqPd6VNzIFEnh1sAiEV+pw21zpxN2xtPPY/iE0wfoEkfK2du8DHDbbx6GycMx0DRapuZbtf/XXuHNulx2XL+XjpeOao5nqebAWfUDlDGixcL3qxmMjB5AJGaTR16XoSuQlcIzHUquX0QlW+qJB9rtvcw7SbQrVoimxYomjNjaHlRt4KcfGPxhwsHllniArzeXVJoCaoRBiRLGCnXirYojsSBHas5BHJJ1CNIWHjT4ybzUcQtTxSnOoO0WRLKJ8BzScbUCVsQCQN32cXyU06LFP0PBOz3ITSYN0Amwovr0CyUXbQ1ki8fAmEbqyBmANRjWjm5+C9kwAZem4rYRmLxfR4AhDOm73DRD7fFsglfnuj0jP4WBk2tWtsRFfzQzQiRN6lr6mXG7K1mRKDkUhOhokZuL1WLxIwY7Or2Q0FQo0r9Pz0WLgMYR5l+Y2bJv8742djUMGyEfCN9veRgWH1lJQVGzWK9sDf+UXYbPyr/4Kw5ooZDrNY4=
  - secure: zGts21h/3hfmTBQvRQ9Be21pE7vQ/vLWeeeTlpO/aNTZIePODlkhqBk9o+H6FJCtQ4hqS2RI8XHQqOjTf+Z8sXUnwsyPURlCByK/VoAefNlrBQAAZFuGuZZdoF1XAN+yo4wweYdzyMrSjsc/Ms03e899sAgL7RplDhj+bTL70/nyR1aGTHkMFsj8gyhEXVcL1dATAB3NDEH0aOGjQRe7152nmQ2B7g5TxFG7+6lHM3eAoMNjAfv9kLW0DXZNb+/wAjv9JrSpLWKiNLwC2n4UgWBHtON/y9/Irc9/0siaApKIQbW9mqu7xFELJKVL1b5Ob57pJSIsRbRQI4KWiGRkdTABBO6pGlvn1kHBPb3w3jK7SJR6Bns68/Kc8CXFGa7+eHZlDsiQFg4J8K77wz11P0Ytu6NR934DuYNAKgXFADpXeKo47KzxjQ3j8AaK6Ih6pmbJD+8M9K1siIAUiN0piiqtQipQJgovoisEIqG+v8w70gqCTyT9X4nIFSqcoBhHhhcCxcPuYXcBUCFF/VaOR+Knqe49r1nfHLeUgbi1sF1Uvh1pzJ1gfo+6nEjAy/4hVmyzC5V8wLfId73DKzMhWS+C/jbG9ynPMIBPruCbNLSaGXvIe+SIp20bq4Tn0T/W3CI8QahMG85d9ess2LP3+lnJahPcSBjjWe/kl8eS0DQ=
sudo: false
python:
- '2.7'
install:
- pip install -r build_requirements.txt
script:
- cd iotilecore && tox && cd ..
- cd transport_plugins/bled112 && tox && cd ../../
deploy:
  skip_cleanup: true
  provider: script
  script: python scripts/release.py $TRAVIS_TAG
  on:
    branch: master
    tags: true
