language: python
sudo: false
python:
- '2.7'
install:
- pip install -r build_requirements.txt
script:
- cd iotilecore && tox && cd ..
- cd transport_plugins/bled112 && tox && cd ../../
deploy:
  skip_cleanup: true
  provider: script
  script: python scripts/release.py $TRAVIS_TAG
  on:
    branch: master
    tags: true
